### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Mlastawi** [Mlastawi/ProjektSsp#1]
- [x] Dorzucić kolejkę FIFO dla odbioru z WBM
- [ ] Możliwość wyboru pracy RAMu:
    - [x] single
    - [ ] row
    - [ ] burst
- [x] Czytanie słów z RAMu od końca
- [x] Blok do obliczania CRC
    - [x] Podstawowe CRC
    - [x] Endianowość
    - [x] Wielosłowowe  #CRC
- [x] Zapis CRC do RAMu
- [ ] Sprawdzanie poprawności kodu CRC
- [ ] Sygnały wyjściowe do STAT
    - [ ] ERR
    - [ ] OK
- [ ] Przerwanie do uC
- [x] Oddzielny niż WB reset dla układu
